spring.application.name=example

spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

application.security.jwt.secret-key=Zm9yTGVhcm5pbmdQdXJwb3NlT25seV9UaGlzS2V5U2hvdWxkQmVMb25nRW5vdWdoMTIzNDU2Nzg5MA==
application.security.jwt.expiration=86400000

server.port=8081